# Generated by Django 4.2 on 2024-04-25 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="created_datetime",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="deadline_datetime",
            new_name="deadline",
        ),
    ]
